#!/bin/bash

# This file is part of the Princeton FCMA Toolbox, (c) 2013 
# written by bdsinger@princeton.edu

#defaults for submission method
USE_QSUB=0
DRY_RUN=0
GEN_TEMPLATE=0
APP=pni_fcma
MPIRUN=mpirun
HOSTFILE=hostfile.txt
ME=$(basename $0)

(( $# == 0 )) && printf "usage: %s jobfile.fcma\n\tPlease see the \"config file\" link at\n\thttp://www.princeton.edu/fcma\n" $(basename $0) && exit 1
JOBFILE=$1

#----------------
hget() {
	hfile=$1
	grep $2 $1 | cut -d: -f2
}

jtemp=$(mktemp tmp.XXXXX)
grep -v '\#' $JOBFILE  | grep '\:[^\w]' > $jtemp

# parse launch metainfo from .fcma file
N=$(hget $jtemp num_processors)
[[ -z $N ]] && echo "num_processors must be specified" && exit 1
M=$(hget $jtemp omp_num_threads)
[[ -z $M ]] && echo "omp_num_threads must be specified" && exit 1
uAPP="$(hget $jtemp exefile)"
[[ -x $uAPP ]] && APP=$uAPP
uQSUB="$(hget $jtemp use_qsub)"
[[ $uQSUB =~ yes ]] && USE_QSUB=1
uDRY="$(hget $jtemp dryrun)"
[[ $uDRY =~ yes ]] && dryecho="echo would run:" || dryecho=""
uOPAL_PREFIX="$(hget $jtemp opal_prefix)"
if [[ -n $uOPAL_PREFIX ]]; then
  if [[ ${uOPAL_PREFIX:0:1} == / ]]; then
    prefix=$uOPAL_PREFIX
  else
    prefix=$PWD/$uOPAL_PREFIX
  fi
  export OPAL_PREFIX=$prefix
  MPIRUN=$prefix/bin/mpirun
fi

if (( USE_QSUB )); then

  rm $jtemp

  # - right now USE_QSUB requires an if-clause for your hostname
  # - could source another script called "qsub.$host" but 
  #   given its "write once, run all the time" nature, better
  #   to inline it here and avoid the added complexity

  shost=$(hostname -s)
  
  if [[ $shost =~ rondo ]]; then

    # ******** RONDO cluster ********

    # gridengine config knows about hosts eligible 
    # for fullcorr project, so hostfile not used here
    $dryecho pni_mpirun -P fullcorr $N $M $APP $JOBFILE

  elif [[ $shost =~ della ]]; then

    # *********** DELLA cluster **********

    which module >/dev/null 2>&1
    (( $? )) && source /usr/share/Modules/init/bash
    module load fcma >/dev/null 2>&1
    (( $? )) && echo "warning: could not load fcma module; check installation"
    which mpirun >/dev/null 2>&1
    (( $? )) && echo "error: mpiexec not in path; please ask sysadmin how to load MPI" && exit 1

    tmpf=$(mktemp)

cat<<EOF >$tmpf

#PBS -l nodes=$N:ppn=$M,walltime=24:00:00
. /usr/share/Modules/init/bash
module load fcma
export OMP_NUM_THREADS=$M
mpirun -bynode -np $N $APP $JOBFILE

EOF

    if (( DRY_RUN == 1 )); then
      echo "would submit the following job script:"
      echo
      echo "----------------BEGIN---------"
      cat $tmpf
      echo "----------------END-----------"
      echo
    else
      jobname="$(basename $JOBFILE)"
      exec qsub -N $jobname $tmpf
    fi

  # elif 
  # *************** YOUR CLUSTER here ************

  else

    # *************** UNKNOWN cluster **************

    echo "unknown host $shost for when USE_QSUB=1 in $(basename $0)"
    exit 1

  fi 

else

  # *********** GENERIC OpenMPI - No cluster scheduler ***********

  uHOSTFILE="$(hget $jtemp hostfile)"
  [[ -n $uHOSTFILE ]] && HOSTFILE=$uHOSTFILE
  [[ -n $dryecho ]] && cat $jtemp
  rm $jtemp

  SUFFIX="$MPIRUN -np $N -hostfile $HOSTFILE $APP $JOBFILE"

  [[ -n $dryecho ]] && $dryecho OMP_NUM_THREADS=$M $SUFFIX && exit

  OMP_NUM_THREADS=$M $SUFFIX

fi

