#!/bin/bash
set -u

#defaults 
USE_QSUB=1
DRY_RUN=0
APP=pni_fcma

(( $# == 0 )) && printf "%s jobfile.fcma. see http://princetonuniversity.github.io/fcma-toolbox for .fcma file format\n" && exit 1
(( $# > 0 )) && JOBFILE=$1
(( $# > 1 )) && [[ $@ =~ noqsub ]] && USE_QSUB=0
(( $# > 1 )) && [[ $@ =~ dry ]] && DRY_RUN=1

# prefix commands that launch jobs with
# dryecho -- on dryrun just prints command
(( DRY_RUN )) && dryecho="echo" || dryecho=""
# or cat script not run it
(( DRY_RUN )) && drycat="cat" || drycat=""

# ----------------
#      list of possible settings
#      and corresponding cmdline flags
# ----------------
declare -a key_and_flags
key_and_flags=(
	omp_num_threads			'OMP_NUM_THREADS='
	num_processors			'-np '
	exefile				' '
	datadir				'-d '
	matrix_format			'-m '
	outputfile			'-t '
	task_type			'-k '
	blockfile			'-b '
	blockdir			'-e '
	rows_per_round			'-s '
	first_left_out_block_id		'-l '
	num_items_held_for_test		'-h '
	is_test_mode			'-c '
	num_folds_in_feature_selection	'-n '
	first_maskfile			'-x '
	second_maskfile			'-y '
	visualize_blockid		'-v '
	visualize_reference		'-r '
)
numflags=${#key_and_flags[@]}

hget() {
	hfile=$1
	grep $2 $1 | cut -d: -f2
}

#----------------

# first app arg in list above is datadir,
# index 8 (if starting from 0) -- row * 2 cols
app_arg_index=6
app_args=""
# get lines that set a value
jtemp=$(mktemp)
grep -v '\#' $JOBFILE  | grep '\:[^\w]' > $jtemp
for (( i=$app_arg_index; i<$numflags; i+=2 )); do
	(( j = i + 1 ))
	# substitute the corresponding flag from above
	key="${key_and_flags[$i]}"
	flag="${key_and_flags[$j]}"
	line="$(grep $key: $jtemp)"
	[[ X != X${line} ]] && app_args="$app_args $(echo $line | sed "s/${key}\:/${flag}/")"
done

N=$(hget $jtemp num_processors)
[[ -z $N ]] && echo "num_processors must be specified" && exit 1
M=$(hget $jtemp omp_num_threads)
[[ -z $M ]] && echo "omp_num_threads must be specified" && exit 1
uAPP="$(hget $jtemp exefile)"
[[ -x $uAPP ]] && APP=$uAPP

if (( USE_QSUB )); then
	# gridengine config knows about hosts eligible 
	# for $PROJECT, so hostfile not used here
	$dryecho pni_mpirun -P fullcorr $N $M $APP $app_args
else
	# Note that this is not used on rondo but could be
	# if gridengine qsub method has issues
	exec "OMP_NUM_THREADS=$M mpiexec -np $N $APP $app_args"
fi

