# if you want to use this file then edit Makefile to include it
# at the top
CXX=/usr/local/bin/g++
MPICXX=/usr/local/bin/mpic++ 
MPIFLAGS=-I/usr/local/include
CXXFLAGS = -I/usr/local/include -O3 -fopenmp -fPIC -g
WARNINGFLAGS = -Wall -Werror -Wextra
LDFLAGS=-L/usr/local/lib
LD_LIBS = -lm -lgoto2 -lz -lniftiio -lznz -lgfortran
