# if you want to use this file then edit Makefile to include it
# at the top
CXX = icc
MPICXX = mpic++
MPIFLAGS = $(LOCAL_CXXFLAGS)
CXXFLAGS = -I/tigress/PNI/include -O3 -fopenmp -fPIC -g
WARNINGFLAGS = -Wall -Werror -Wextra
LDFLAGS = -L/tigress/PNI/lib $(LOCAL_LDFLAGS)
LD_LIBS = -lgoto2 -lniftiio -lznz -lz -lgfortran
